DROP TABLE IF EXISTS users, categories, events, compilations, compilation_events, locations, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
email varchar(255)                           NOT NULL UNIQUE,
name varchar(255)                                    NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
name varchar(50)                             NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations(
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    lat         FLOAT NOT NULL,
    lon         FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
id BIGINT             GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
annotation varchar(2000)                                        NOT NULL,
category_id BIGINT REFERENCES categories (id) ON DELETE NO ACTION  NOT NULL,
description varchar(7000)                                       NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE                          NOT NULL,
confirmed_requests INT,
initiator_id BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
lat                        DEC NOT NULL,
lon                        DEC NOT NULL,
paid boolean                                      NOT NULL DEFAULT false,
participant_limit INT                                 NOT NULL DEFAULT 0,
published_on TIMESTAMP                                 WITHOUT TIME ZONE,
request_moderation boolean                         NOT NULL DEFAULT true,
state varchar(255)                            NOT NULL DEFAULT 'PENDING',
title varchar(120)                                              NOT NULL,
created_on TIMESTAMP                          WITHOUT TIME ZONE NOT NULL,
views INTEGER
);

CREATE TABLE IF NOT EXISTS compilations (
id BIGINT     GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
pinned boolean                            NOT NULL DEFAULT false,
title varchar(50)                                       NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
id BIGINT                    GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
event BIGINT             NOT NULL REFERENCES events (id) ON DELETE CASCADE,
requester BIGINT          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
status varchar(255)                             NOT NULL DEFAULT 'PENDING',
created TIMESTAMP                          WITHOUT TIME ZONE NOT NULL,
CONSTRAINT requests_pk PRIMARY KEY (requester, event)
);

CREATE TABLE IF NOT EXISTS comp_events (
id BIGINT                    GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
comp_id BIGINT REFERENCES compilations (id) ON DELETE CASCADE NOT NULL,
event_id BIGINT REFERENCES events (id) ON DELETE CASCADE NOT NULL,
PRIMARY KEY(comp_id, event_id)
);

create TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    event_id BIGINT,
    author_id BIGINT,
    created TIMESTAMP,
    is_response BOOLEAN,
    parent_comment_id BIGINT,
    CONSTRAINT fk_com_to_events FOREIGN KEY(event_id) REFERENCES events(id) ON delete CASCADE,
    CONSTRAINT fk_com_to_users FOREIGN KEY(author_id) REFERENCES users(id) ON delete CASCADE
);